/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import demotica.Dashboard;
import demotica.File;
import demotica.Home;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HenrikM
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        carregar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDivision = new javax.swing.JPanel();
        addB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lMessage = new javax.swing.JLabel();
        updateB = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        removeB = new javax.swing.JButton();
        tfWindows = new javax.swing.JTextField();
        comboFloor = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDivisions = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfLights = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        jMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        carregar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bar = new javax.swing.JProgressBar();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDivision.setVisible(false);
        jDivision.setEnabled(false);

        addB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addB.setText("Adicionar");
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setText("DIVISÕES");

        jButton3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton3.setText("Concluido");

        lMessage.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lMessage.setForeground(new java.awt.Color(255, 0, 51));
        lMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        updateB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        updateB.setText("Atualizar");
        updateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Nº de janelas:");

        removeB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        removeB.setText("Remover");
        removeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBActionPerformed(evt);
            }
        });

        comboFloor.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        comboFloor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFloorActionPerformed(evt);
            }
        });

        tblDivisions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Piso", "Nº de portas", "Porta p/ o exterior", "Porta de entrada", "Nº de janelas", "Nº de luzes"
            }
        ));
        tblDivisions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDivisionsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDivisions);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Nome:");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Nº de luzes:");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Piso:");

        javax.swing.GroupLayout jDivisionLayout = new javax.swing.GroupLayout(jDivision);
        jDivision.setLayout(jDivisionLayout);
        jDivisionLayout.setHorizontalGroup(
            jDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDivisionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addGroup(jDivisionLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDivisionLayout.createSequentialGroup()
                        .addComponent(lMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jDivisionLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jDivisionLayout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(jLabel8))
                                .addComponent(jLabel7))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(tfWindows)
                            .addComponent(tfLights))
                        .addGap(18, 18, 18)
                        .addGroup(jDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDivisionLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboFloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 289, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDivisionLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeB)))))
                .addContainerGap())
        );
        jDivisionLayout.setVerticalGroup(
            jDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDivisionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(comboFloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfWindows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfLights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addB)
                    .addComponent(updateB)
                    .addComponent(removeB))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jMain.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 48)); // NOI18N
        jLabel1.setText("Inteligente");
        jMain.add(jLabel1);
        jLabel1.setBounds(220, 150, 280, 70);

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 48)); // NOI18N
        jLabel2.setText("Habitação");
        jMain.add(jLabel2);
        jLabel2.setBounds(140, 70, 250, 70);

        carregar.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        carregar.setText("Carregar");
        jMain.add(carregar);
        carregar.setBounds(300, 280, 60, 18);

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("app@masters: Francis Simas; Henrique Melo; Rolfo Melo");
        jMain.add(jLabel5);
        jLabel5.setBounds(270, 380, 310, 13);

        bar.setStringPainted(true);
        jMain.add(bar);
        bar.setBounds(170, 300, 310, 20);

        jButton2.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jButton2.setText("Criar Habitação");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jMain.add(jButton2);
        jButton2.setBounds(170, 330, 140, 30);

        jButton1.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jButton1.setText("Carregar Habitação");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jMain.add(jButton1);
        jButton1.setBounds(320, 330, 160, 30);
        jMain.add(jLabel3);
        jLabel3.setBounds(10, 0, 590, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMain, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDivision, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMain, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Dashboard.carregarDados();
        new Thread(new Timer()).start();
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jMain.setVisible(false);
        jDivision.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
        lMessage.setText("");
        DefaultTableModel model=(DefaultTableModel)tblDivisions.getModel();
        if(!tfName.getText().trim().equals("")){
            model.addRow(new Object[]{tfName.getText(), comboFloor.getSelectedItem().toString(), tfWindows.getText(), tfLights.getText()});

        }else{
            lMessage.setText("O nome da divisão não deve ser deixado em branco!");
        }

    }//GEN-LAST:event_addBActionPerformed

    private void updateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBActionPerformed
        DefaultTableModel model=(DefaultTableModel)tblDivisions.getModel();
        if(tblDivisions.getSelectedRow()==-1){
            if(tblDivisions.getRowCount()==0){
                lMessage.setText("A tabela está vazia!");
            }else{
                lMessage.setText("Deve selecionar uma divisão!");
            }
        }else{
            model.setValueAt(tfName.getText(), tblDivisions.getSelectedRow(), 0);
            model.setValueAt(comboFloor.getSelectedItem().toString(), tblDivisions.getSelectedRow(), 1);
            model.setValueAt(tfWindows.getText(), tblDivisions.getSelectedRow(), 2);
            model.setValueAt(tfLights.getText(), tblDivisions.getSelectedRow(), 3);
        }
    }//GEN-LAST:event_updateBActionPerformed

    private void removeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBActionPerformed
        DefaultTableModel model=(DefaultTableModel)tblDivisions.getModel();
        if(tblDivisions.getSelectedRow()==-1){
            if(tblDivisions.getRowCount()==0){
                lMessage.setText("A tabela está vazia!");
            }else{
                lMessage.setText("Deve selecionar uma divisão!");
            }
        }else{
            model.removeRow(tblDivisions.getSelectedRow());
        }
    }//GEN-LAST:event_removeBActionPerformed

    private void comboFloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFloorActionPerformed
        
    }//GEN-LAST:event_comboFloorActionPerformed

    private void tblDivisionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDivisionsMouseClicked
        DefaultTableModel model=(DefaultTableModel)tblDivisions.getModel();
        tfName.setText(model.getValueAt(tblDivisions.getSelectedRow(), 0).toString());
        comboFloor.setSelectedItem(model.getValueAt(tblDivisions.getSelectedRow(), 1).toString());
        tfWindows.setText(model.getValueAt(tblDivisions.getSelectedRow(), 2).toString());
        tfLights.setText(model.getValueAt(tblDivisions.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tblDivisionsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    
    private class Timer implements Runnable{

        @Override
        public void run() {
            for (int i=1; i<=100;i++){
                bar.setValue(i);
                bar.repaint();
                try{
                Thread.sleep(10);
                if(i==100){
                    jMain.setVisible(false);
                    jDivision.setVisible(true);
                    nFloors();
                }
                }catch(InterruptedException e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
 
    }
    
    private void nFloors(){
        for(int i=0;i<Dashboard.getHome().getnFloors();i++)
            comboFloor.addItem(i);
    }
    
    private void prepPane() {
        jMain.setVisible(false);
        jDivision.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addB;
    private javax.swing.JProgressBar bar;
    private javax.swing.JLabel carregar;
    private javax.swing.JComboBox comboFloor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jDivision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lMessage;
    private javax.swing.JButton removeB;
    private javax.swing.JTable tblDivisions;
    private javax.swing.JTextField tfLights;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfWindows;
    private javax.swing.JButton updateB;
    // End of variables declaration//GEN-END:variables
}
